export const NOT_FOUND_INDEX = -1;
export const NOT_FOUND = 404;

export const INCREMENT = 1;
export const DECREMENT = -1;
export const ZERO = 0;
export const HUNDRED = 100;

export const CAR_PER_PAGE = 7;
export const WINNER_PER_PAGE = 10;

export const MAX_COLOR_COMPONENT = 256;

export const CAR_NAMES: string[] = [
  'Toyota',
  'Honda',
  'BMW',
  'Mercedes-Benz',
  'Ford',
  'Chevrolet',
  'Audi',
  'Nissan',
  'Volkswagen',
  'Subaru',
  'Hyundai',
  'Kia',
  'Mazda',
  'Lexus',
  'Jeep',
  'Volvo',
  'Tesla',
  'Porsche',
  'Ferrari',
  'Lamborghini',
];

export const CAR_MODELS: { [key: string]: string[] } = {
  Toyota: [
    'Camry',
    'Corolla',
    'Rav4',
    'Prius',
    'Highlander',
    'Tacoma',
    'Tundra',
    'Sienna',
  ],
  Honda: [
    'Civic',
    'Accord',
    'CR-V',
    'Pilot',
    'Odyssey',
    'Fit',
    'HR-V',
    'Ridgeline',
  ],
  BMW: [
    '3 Series',
    '5 Series',
    'X3',
    'X5',
    '7 Series',
    'X1',
    'X7',
    'M3',
    'M5',
    'i3',
    'i8',
  ],
  'Mercedes-Benz': [
    'C-Class',
    'E-Class',
    'S-Class',
    'GLC',
    'GLE',
    'GLA',
    'GLS',
    'G-Class',
    'CLA',
    'A-Class',
  ],
  Ford: [
    'F-150',
    'Mustang',
    'Escape',
    'Explorer',
    'Focus',
    'Fusion',
    'Edge',
    'Ranger',
    'Bronco',
    'Expedition',
  ],
  Chevrolet: [
    'Silverado',
    'Equinox',
    'Tahoe',
    'Malibu',
    'Traverse',
    'Camaro',
    'Colorado',
    'Suburban',
  ],
  Audi: ['A4', 'A6', 'Q5', 'Q7', 'Q3', 'A3', 'A5', 'Q8', 'A7', 'E-Tron', 'RS7'],
  Nissan: [
    'Altima',
    'Maxima',
    'Rogue',
    'Sentra',
    'Pathfinder',
    'Versa',
    'Murano',
    'Titan',
    'Frontier',
    'Leaf',
  ],
  Volkswagen: [
    'Jetta',
    'Passat',
    'Tiguan',
    'Atlas',
    'Golf',
    'Arteon',
    'ID.4',
    'Taos',
    'Atlas Cross Sport',
  ],
  Subaru: [
    'Outback',
    'Forester',
    'Impreza',
    'Crosstrek',
    'Legacy',
    'WRX',
    'Ascent',
    'BRZ',
  ],
  Hyundai: [
    'Elantra',
    'Sonata',
    'Tucson',
    'Santa Fe',
    'Kona',
    'Palisade',
    'Veloster',
  ],
  Kia: [
    'Sorento',
    'Sportage',
    'Forte',
    'Optima',
    'Soul',
    'Telluride',
    'Stinger',
    'Cadenza',
  ],
  Mazda: ['Mazda3', 'Mazda6', 'CX-5', 'CX-9', 'CX-30', 'MX-5 Miata'],
  Lexus: ['ES', 'RX', 'NX', 'IS', 'UX', 'LS', 'LC', 'GX', 'LX'],
  Jeep: [
    'Wrangler',
    'Grand Cherokee',
    'Cherokee',
    'Renegade',
    'Compass',
    'Gladiator',
  ],
  Volvo: ['XC90', 'XC60', 'XC40', 'S60', 'S90', 'V60', 'V90'],
  Tesla: ['Model 3', 'Model S', 'Model X', 'Model Y'],
  Porsche: [
    '911',
    'Cayenne',
    'Panamera',
    'Macan',
    'Taycan',
    'Boxster',
    'Cayman',
  ],
  Ferrari: [
    '488 GTB',
    'F8 Tributo',
    '812 Superfast',
    'Portofino',
    'SF90 Stradale',
  ],
  Lamborghini: ['Aventador', 'Huracan', 'Urus'],
};
